/** Swipes required to finish onboarding (step 6). */
export const ONBOARDING_SWIPES_REQUIRED = 25;

/** Swipes required to unlock Radar and related “100 swipe” UX in the main app. */
export const RADAR_SWIPES_THRESHOLD = 100;

export const ONBOARDING_STORAGE_KEYS = {
  complete: 'encorely_onboarding_complete',
  preferences: 'encorely_onboarding_preferences',
} as const;

export interface OnboardingArtistPick {
  id: string;
  name: string;
}

export interface OnboardingPreferences {
  artists: OnboardingArtistPick[];
  genres: string[];
}

/** Spotify recommendation seed genres (subset of official seed genres). */
export const SPOTIFY_SEED_GENRES: readonly string[] = [
  'acoustic',
  'afrobeat',
  'alt-rock',
  'alternative',
  'ambient',
  'black-metal',
  'bluegrass',
  'blues',
  'breakbeat',
  'british',
  'cantopop',
  'chicago-house',
  'children',
  'chill',
  'classical',
  'club',
  'comedy',
  'country',
  'dance',
  'dancehall',
  'death-metal',
  'deep-house',
  'detroit-techno',
  'disco',
  'disney',
  'drum-and-bass',
  'dub',
  'dubstep',
  'edm',
  'electro',
  'electronic',
  'emo',
  'folk',
  'forro',
  'french',
  'funk',
  'garage',
  'german',
  'gospel',
  'goth',
  'grindcore',
  'grunge',
  'guitar',
  'happy',
  'hard-rock',
  'hardcore',
  'hardstyle',
  'heavy-metal',
  'hip-hop',
  'honky-tonk',
  'house',
  'idm',
  'indian',
  'indie',
  'indie-pop',
  'industrial',
  'iranian',
  'j-dance',
  'j-idol',
  'j-pop',
  'j-rock',
  'jazz',
  'k-pop',
  'kids',
  'latin',
  'latino',
  'malay',
  'mandopop',
  'metal',
  'metalcore',
  'minimal-techno',
  'mpb',
  'new-age',
  'opera',
  'pagode',
  'party',
  'piano',
  'pop',
  'pop-film',
  'power-pop',
  'progressive-house',
  'psych-rock',
  'punk',
  'punk-rock',
  'r-n-b',
  'reggae',
  'reggaeton',
  'rock',
  'rock-n-roll',
  'rockabilly',
  'romance',
  'sad',
  'salsa',
  'samba',
  'sertanejo',
  'show-tunes',
  'singer-songwriter',
  'ska',
  'sleep',
  'songwriter',
  'soul',
  'spanish',
  'study',
  'swedish',
  'synth-pop',
  'tango',
  'techno',
  'trance',
  'trip-hop',
  'turkish',
  'world-music',
] as const;
